"""empty message

Revision ID: 62b232a21877
Revises: d67af15bfed9
Create Date: 2024-04-20 22:02:29.916626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b232a21877'
down_revision = 'd67af15bfed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sas', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('programme', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mise', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('mise')
        batch_op.drop_column('programme')
        batch_op.drop_column('sas')

    # ### end Alembic commands ###
