"""empty message

Revision ID: bbf4ef220036
Revises: 62b232a21877
Create Date: 2024-04-20 22:08:05.095448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf4ef220036'
down_revision = '62b232a21877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('sas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sas', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
